//
//  ArticleViewController.swift
//  SJA
//
//  Created by Rosalind Ellis on 7/15/15.
//  Copyright (c) 2015 Rosalind Ellis. All rights reserved.
//

import WebKit

class ArticleViewController: UIViewController {

    var webView: WKWebView! //for displaying web content
    var chosenArticle: String?
    
    @IBOutlet weak var backButton: UIBarButtonItem!
    @IBOutlet weak var forwardButton: UIBarButtonItem!
    @IBOutlet weak var reloadButton: UIBarButtonItem!
    @IBOutlet weak var progressView: UIProgressView!
    
    // initializes webView with frame size zero
    required init(coder aDecoder: NSCoder) {
        self.webView = WKWebView(frame: CGRectZero)
        super.init(coder: aDecoder)
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        // adds webview to main view below the progress view
        view.insertSubview(webView, belowSubview: progressView)
        
        // sets constraints of webview
        webView.setTranslatesAutoresizingMaskIntoConstraints(false) //disables autogenerated layout
        let height = NSLayoutConstraint(item: webView, attribute: .Height, relatedBy: .Equal, toItem: view, attribute: .Height, multiplier: 1, constant: -44) // define height equal to the toolbar
        let width = NSLayoutConstraint(item: webView, attribute: .Width, relatedBy: .Equal, toItem: view, attribute: .Width, multiplier: 1, constant: 0) // define width equal to superview
        view.addConstraints([height, width]) //adds constraints to view
        
        // add class as observers
        webView.addObserver(self, forKeyPath: "loading", options: .New, context: nil)
        webView.addObserver(self, forKeyPath: "estimatedProgress", options: .New, context: nil)
        
        // creates and loads article link
        let url = NSURL(string: chosenArticle!)
        let requestObj = NSURLRequest(URL: url!)
        webView.loadRequest(requestObj)

        //buttons are definitely not enabled
        backButton.enabled = false
        forwardButton.enabled = false
        
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    // MARK: - Loading Property
    
    override func observeValueForKeyPath(keyPath: String, ofObject object: AnyObject, change: [NSObject : AnyObject], context: UnsafeMutablePointer<Void>) {
        backButton.enabled = webView.canGoBack
        forwardButton.enabled = webView.canGoForward
        
        // updates progressView to the estimated progress
        if keyPath == "estimatedProgress" {
            progressView.hidden = webView.estimatedProgress == 1
            progressView.setProgress(Float(webView.estimatedProgress), animated: true)
        }
    }
    
    // resets progressView after each request
    func webView(webView: WKWebView!, didFinishNavigation navigation: WKNavigation!) {
        progressView.setProgress(0.0, animated: false)
    }
    
    // MARK: - Toolbar Actions
    
    @IBAction func back(sender:UIBarButtonItem) {
        webView.goBack()
    }
    
    @IBAction func forward(sender:UIBarButtonItem) {
        webView.goForward()
    }
    
    @IBAction func reload(sender:UIBarButtonItem) {
        let request = NSURLRequest(URL: webView.URL!)
        webView.loadRequest(request)
    }
    

    /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        // Get the new view controller using segue.destinationViewController.
        // Pass the selected object to the new view controller.
    }
    */

}
